project_id = "vkfmtrovrxgalhekzfsu"

[functions.media-proxy]
verify_jwt = false

[functions.notify-admins-pending-script]
verify_jwt = false

[functions.notify-team-script-approved]
verify_jwt = false

[functions.send-approval-reminders]
verify_jwt = false

[functions.trigger-video-generation]
verify_jwt = false

[functions.video-generation-callback]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false
