// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkfmtrovrxgalhekzfsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZm10cm92cnhnYWxoZWt6ZnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTA5MzEsImV4cCI6MjA2NzQ4NjkzMX0.UgrqUj1PdficRXSPnk1XDjKUalvOxftl8tGu14euEhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});